# Filename: execute_python_script.yml
---
- hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Transfer Python script to remote server
      copy:
        src: "/var/lib/jenkins/workspace/Wordpress/scripts/install_wordpress.py"
        dest: /tmp/install_wordpress.py
        mode: '0755'

    - name: Execute Python script to install WordPress
      command: python3 /tmp/install_wordpress.py